# Generated by Django 5.0.6 on 2024-05-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number_of_guards', models.IntegerField()),
                ('gate_type', models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit'), ('Both', 'Both')], max_length=10)),
                ('shift_time', models.CharField(choices=[('24 hours', '24 hours'), ('12 hours', '12 hours'), ('8 hours', '8 hours')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.gate')),
            ],
        ),
    ]
